# Dockerfile for the database container
FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY database.py database.py
COPY .env .env
COPY wire.py wire.py
COPY markups.py markups.py
COPY constants.py constants.py